// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using WatchKit;

namespace SmartLabWatchKitExtension
{
	public partial class ReqIntCtrl : WKInterfaceController
	{
		public ReqIntCtrl (IntPtr handle) : base (handle)
		{
		}
	}
}
