// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;
using System.Linq;
using Foundation;
using WatchKit;

namespace SmartLabWatchKitExtension
{
	public partial class ReqIntCtrl : WKInterfaceController
	{
		private WKInterfaceButton[] Buttons = new WKInterfaceButton[9];

		public ReqIntCtrl (IntPtr handle) : base (handle)
		{
			
		}

		public override void Awake (NSObject context)
		{
			base.Awake (context);
			NSTimer.CreateRepeatingScheduledTimer (6, delegate {
				foreach (var b in Buttons) {
					b.SetTitle ("??");
				}

				InvokeInBackground(async () => {
					var requests = await Api.GetRequests();
					if (KeyStore.BizCalcOnly) {
						requests = requests.Where(
							x=>x.IsBizCalc()).ToList();
					}

					if (KeyStore.HideBizCalc) {
						requests = requests.Where(
							x=> x.IsBizCalc() == false
						).ToList();
					}

					InvokeOnMainThread(delegate {
						if (Api.Updated != new DateTime(0)) {
							for (int i = 0; i < Math.Min(requests.Count, 9); ++i)
							{
								if (requests[i].IsBizCalc()) {
									this.Buttons[i].SetBackgroundColor(UIColor.FromRGB (111, 38, 135));
								} else {
									this.Buttons[i].SetBackgroundColor(UIColor.Red);
								}
								this.Buttons[i].SetTitle(requests[i].Location);
							}
							this.timeLbl.SetText(Api.Updated.ToString("T"));
						} else {
							this.timeLbl.SetText("Update Failed");
						}
					});
				});
			});
		}

		public override void WillActivate ()
		{
			// This method is called when the watch view controller is about to be visible to the user.
			//Console.WriteLine ("{0} will activate", this);
			this.Buttons = new WKInterfaceButton[] {
				this.ReqA,
				this.ReqB,
				this.ReqC,
				this.ReqD,
				this.ReqE,
				this.ReqF,
				this.ReqG,
				this.ReqH,
				this.ReqI
			};

			foreach (var b in Buttons) {
				b.SetTitle ("??");
			}

			InvokeInBackground (async delegate {
				var requests = await Api.GetRequests();
				InvokeOnMainThread(delegate {
					if (Api.Updated != new DateTime(0)) {
						for (int i = 0; i < Math.Min(requests.Count, 9); ++i)
						{
							this.Buttons[i].SetTitle(requests[i].Location);
						}
						this.timeLbl.SetText(Api.Updated.ToString("T"));
					} else {
						this.timeLbl.SetText("Update Failed");
					}
				});
			});
		}

		public override void DidDeactivate ()
		{
			// This method is called when the watch view controller is no longer visible to the user.
			//Console.WriteLine ("{0} did deactivate", this);
			//this.Timer.Dispose ();
		}
	}
}
