// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;

namespace SmartLab
{
	public partial class CalViewCtrl : UITableViewController
	{
		public List<Event> Events = new List<Event> ();
		public CalViewCtrl (IntPtr handle) : base (handle)
		{
			this.Title = "Calendar";
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			this.SearchDisplayController.SearchResultsTableView.RowHeight = this.TableView.RowHeight;

			this.Events = Cache.GetEvents ();
			this.SearchDisplayController.SearchBar.TextChanged += (sender, e) => {
				this.SearchDisplayController.SearchResultsTableView.Source = new CalSource(this.Events, e.SearchText);
				this.SearchDisplayController.SearchResultsTableView.ReloadData();
			};

			this.TableView.Source = new CalSource (this.Events);
			this.TableView.ReloadData ();

			InvokeInBackground (async delegate {
				InvokeOnMainThread(delegate {
					UIApplication.SharedApplication.NetworkActivityIndicatorVisible = true;
				});
				var c = await Api.GetCalendar();
				if (c.Count > 0) {
					Cache.SetEvents(c);
				}
				this.Events = Cache.GetEvents();
				InvokeOnMainThread(delegate {
					this.TableView.Source = new CalSource (this.Events);
					this.TableView.ReloadData ();
					UIApplication.SharedApplication.NetworkActivityIndicatorVisible = false;
				});
			});
		}
	}
}
