// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace SmartLab
{
	public partial class RequestsViewCtrl : UITableViewController
	{
		public RequestsViewCtrl (IntPtr handle) : base (handle)
		{
		}
	}
}
