// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace SmartLab
{
	public partial class ScheduleViewCtrl : UIViewController
	{
		private UIWebView _webView;

		public ScheduleViewCtrl (IntPtr handle) : base (handle)
		{
			this.Title = "Schedule";
			this._webView = new UIWebView (this.View.Frame);
			this.Add (this._webView);
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			this._webView.LoadRequest (new NSUrlRequest (new NSUrl (Api.SCHEDULE_URL)));
		}
	}
}
